spring:
  application:
    name: api
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost/database"
    username: username
    password: password
    hikari:
      connectionInitSql: "SET NAMES utf8mb4"

  jpa:
    hibernate:
      ddl-auto: validate # validate, create, create-drop., update, none
    # `hibernate.ddl-auto` 설정이 `generate-ddl`보다 우선하므로 설정이 무시됨
    # generate-ddl: true
    show-sql: true
    open-in-view: false # 허용 시 뷰 렌더링 중에도 지연 로딩 쿼리가 실행될 수도 있음

web-config:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:8080
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: '*'
    max-age: 3600

logging:
  level:
    root: INFO
